name: Update GitHub Stats
on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    # Remove the restrictive condition that was causing the issue
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Fetch stats from your API
        id: get-stats
        run: |
          # Add timeout and retry for reliability
          response=$(curl -s --max-time 30 --retry 3 "https://gitcommittracker.up.railway.app/norizara")
          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$response" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "API call completed for ${{ github.event_name }} event"

      - name: Update README with new stats
        env:
          API_RESPONSE: "${{ steps.get-stats.outputs.response }}"
        run: |
          python scripts/update_readme.py

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet README.md || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          
          # Different commit messages based on trigger
          if [ "${{ github.event_name }}" = "push" ]; then
            git commit -m "📈 Auto-update stats after code push - $(date +'%Y-%m-%d %H:%M UTC')"
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            git commit -m "📈 Daily stats update - $(date +'%Y-%m-%d %H:%M UTC')"
          else
            git commit -m "📈 Manual stats update - $(date +'%Y-%m-%d %H:%M UTC')"
          fi
          
          git push
